
modLoader="javafml"
loaderVersion="[36,)"
license="Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License"
[[mods]]
modId="crashlogadditions"
version="${file.jarVersion}"
displayName="CrashLog Additions"
authors="Dyonovan"
description='''
Allows pack makers to add addition information to crash logs.
'''
[[dependencies.crashlogadditions]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

